In [ ]:
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

In [75]:
size = 5
rand_matrix = np.random.rand(5,5)
for i in range(1,size):
    for j in range(0, i+1):
        if (i == j):
            rand_matrix[i][j] = 0
        else:
            rand_matrix[i][j] = -rand_matrix[j][i]

print(rand_matrix)
print(np.array_equal(rand_matrix, rand_matrix.T))

[[ 0.34992733  0.42130124  0.94864437  0.18131307  0.17856231]
 [-0.42130124  0.          0.36504332  0.17061309  0.21325162]
 [-0.94864437 -0.36504332  0.          0.37373643  0.98914255]
 [-0.18131307 -0.17061309 -0.37373643  0.          0.0679095 ]
 [-0.17856231 -0.21325162 -0.98914255 -0.0679095   0.        ]]
False


In [84]:
def anti_diagonal(size):
    matrix = np.eye(size)
    for i in range(size):
        matrix[i][size - 1 - i] = 1
        matrix[i][i] = 0
    return matrix

print(anti_diagonal(6))

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [89]:
n = 10

M = np.zeros((n,n))
M[3:7,3:7] = 1
M[1:3, 4:6] = 7
M[4:6, 7:9] = 5
M

J = anti_diagonal(n)
print(J@M@J)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 5. 5. 1. 1. 1. 1. 0. 0. 0.]
 [0. 5. 5. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 7. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# opening a figure as an RGB file
img1 = np.array(Image.open('Kyoto.jpg')) 
print ("shape:", img1.shape)
print ("type:", type(img1)) 
print ("type:", img1.dtype) 