# <center> Some useful NumPy commands

In [1]:
import numpy as np

<div style="text-align: right"> :הקישור לדוקומנטציה </div>

NumPy Reference documentation:

* On the web:(http://docs.scipy.org/)

* Interactive help:

In [ ]:
np.array

<function numpy.array>

## <div style="text-align: right"> :יצירת מערכים מרשימה </div>

<div style="text-align: right"> חד-ממדי $\bullet$</div>

In [6]:
a = np.array([-2, 2, 0, 5])
a

array([-2,  2,  0,  5])

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [9]:
len(a)

4

<div style="text-align: right"> דו-ממדי $\bullet$</div>

In [10]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
len(b)

2

## <div style="text-align: right"> :פונקציות ליצירת מערכים </div>

<div style="text-align: right"> :יצירת מערך עם קביעת הרווחים $\bullet$</div>

In [14]:
a = np.arange(10)  
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.arange(1, 9, 2)  
b

array([1, 3, 5, 7])

<div style="text-align: right"> :לפי מספר הנקודות $\bullet$</div>

In [16]:
c = np.linspace(0, 1, 6)  
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

<div style="text-align: right"> :מערכים סטנדרטיים $\bullet$</div>

In [21]:
a = np.zeros((2, 2))  
a

array([[0., 0.],
       [0., 0.]])

In [23]:
x = np.empty(5)  
x

array([0. , 0.2, 0.4, 0.6, 0.8])

In [24]:
c = np.ones((3, 3))  
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
d = np.eye(4)    
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

<div style="text-align: right"> :מערכים אקראיים $\bullet$</div>

In [27]:
a = np.random.rand(4)  # sample from uniform distribution in [0, 1]
a

array([0.86061889, 0.52789169, 0.55370322, 0.56481348])

In [28]:
b = np.random.randn(4)  # sample from Gaussian distribution
b

array([-0.88898252, -1.41479073, -0.49011411,  1.54330347])

## <div style="text-align: right"> אינדוקס וחיתוך </div>

<div style="text-align: right"> צורת הגישה לאיברים במערך</div>

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0], a[2], a[-1]

In [ ]:
a[2:9:3] 

In [ ]:
a[::-1]

In [ ]:
a[::2]

<div style="text-align: right"> שימו לב שבמערך דו-ממדי, הממד הראשון מתייחס לשורות והשני לעמודות</div>

In [ ]:
b = np.diag(np.arange(4))
b

In [ ]:
b[1, 1]

In [ ]:
b[2, 1]

In [ ]:
b[1]

In [ ]:
b[:, 2]

<div style="text-align: right"> .אינדוקס באמצעות ״מסיכה בוליאנית״ </div>

<div style="text-align: right"> .דוגמא: במערך נתון נמצא את כל האיברים המתחלקים בשלוש  </div>

In [ ]:
np.random.seed(3)  # initilizing the pseudo-random number generator
a = np.random.randint(0, 20, 15)  # low=0, high=20, size=15
a

<div style="text-align: right"> יצירת ״מסכה״ - מערך בוליאני, בו ערך ״אמת״ מחליף את האיבר המתחלק בשלוש במערך המקורי    </div>

In [ ]:
mask = (a % 3 == 0)
mask

<div style="text-align: right"> אינדוקס ע״י מערך המסכה יוצר תת-מערך של המאיברים המתחלקים בשלוש  </div>

In [ ]:
extract_from_a = a[mask]  # extract a sub-array with the mask
extract_from_a

<div style="text-align: right"> :אפשר לעשות זאת ישירות  </div>

In [ ]:
a[a % 3 == 0]

<div style="text-align: right"> אינדוקס באמצעות מערך של מספרים שלמים  </div>

In [ ]:
a = np.arange(0, 100, 10)
a

In [ ]:
a[[2, 3, 2, 4, 2]]  # [2,3,2,4,2]is a Python list

In [ ]:
a[[9, 7]] = -100
a

## <div style="text-align: right"> פעולות על מערכים </div>

<div style="text-align: right"> פעולות אריתמטיות על איברי המערך ובין מערכים $\bullet$ </div>

In [ ]:
a = np.array([1, 2, 3, 4])
a+2

In [ ]:
-2*a

In [ ]:
2**a

In [ ]:
b = np.ones(4) + 1
b

In [ ]:
a-b

In [ ]:
a*b

<div style="text-align: right">! במקרה זה, חשוב לשים לב שהמערכים הם מאותו גודל  </div>

In [ ]:
j = np.arange(5)
2**(j + 1) - j

<div style="text-align: right">:השוואות $\bullet$ </div>

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

In [ ]:
a > b

In [ ]:
np.array_equal(a, b)

In [ ]:
c = np.array([1, 2, 3, 4])
np.array_equal(a, c)

<div style="text-align: right">:פעולות לוגיות $\bullet$ </div>

In [ ]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [ ]:
np.logical_or(a, b)

In [ ]:
np.logical_and(a, b)

<div style="text-align: right", >:פונקציות שונות $\bullet$ </div>

In [ ]:
a = np.linspace(-np.pi, np.pi, 10)
np.sin(a)

In [ ]:
a = np.arange(1, 10)
np.log(a)

In [ ]:
np.exp(a)

 <div style="text-align: right"> פעולות נוספות $\bullet$ </div>

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

In [ ]:
x.sum()

In [ ]:
y = np.array([[1, 2], [6, 3]])
y

In [ ]:
y.sum(axis=0)  # columns (first dimension)

In [ ]:
y.sum(axis=1)  # rows (second dimension)

In [ ]:
y.min()

In [ ]:
y.max()

In [ ]:
np.argmin(y, axis=1)  # returns the indices of the minimum values along an axis

In [ ]:
np.argmax(y, axis=0)

In [ ]:
x = np.array([1, 2, 3, 1])
x.mean()

In [ ]:
x.std()

In [ ]:
y = np.array([[1, 2, 3], [5, 6, 1]])
np.mean(y, axis=-1)  # last axis

## <div style="text-align: right"> מיון מערכים </div>

In [ ]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a

In [ ]:
b = np.sort(a, axis=1)  # sorting along an axis
b

In [ ]:
c = np.sort(a, axis=0)
c

 <div style="text-align: right"> מיון עם מסכה </div>

In [ ]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)  # indices are sorted
j

In [ ]:
a[j]  # the array is sorted